tap 'nodenv/nodenv'

brew 'heroku'
brew 'imagemagick'
brew 'nodenv-aliases'
brew 'nodenv-vars'
brew 'nodenv'
brew 'parity'
brew 'rbenv-aliases'
brew 'rbenv-vars'
brew 'rbenv'
brew 'ruby-build'
brew 'yarn'
brew 'zplug'

brew 'postgresql', start_service: false
brew 'mysql', start_service: false

# Build tools and libs
brew 'coreutils'
brew 'gmp'
brew 'libyaml'
brew 'makedepend'
brew 'pkg-config'
brew 'readline'

cask '1password'
cask 'alfred'
cask 'captain'
cask 'cyberduck'
cask 'docker'
cask 'firefox'
cask 'google-chrome'
cask 'harvest'
cask 'iterm2'
cask 'notion'
cask 'postico'
cask 'postman'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'tunnelblick'
cask 'typora'
cask 'visual-studio-code'
cask 'vlc'

